### PR TITLE
Bubble Display Range

### PR DESCRIPTION
**Pull request by SaltSouls**
This adds the option for players to configure from how far away they want the bubbles to display. I think it helps with some screen clutter(especially when there are lots of NPCs in one area) and also allows for a little more immersion. Still allows them to set the range high enough to cover the entire display area if they so choose.

### CODE REVIEW

**Review by urbanyeti — CHANGES_REQUESTED** [review]
This is awesome!! I love the idea. I was just looking at your previous PR after getting back into it so I'm glad you already got my new changes merged in!

One quick thing-- can you re-add `BetterFriendship/BetterFriendship.sln` and `BetterFriendship/BetterFriendship.csproj` (I think they were missed when changing the name back).

**Comment by SaltSouls** [comment]
The csproj file contains a path to my game that should be removed. I only had to add it because my IDE wasn't automatically detecting SDVs location.

**Comment by urbanyeti** [comment]
Oh no-- did you already get rid of your fork? I need to reset the branch and was going to ask you to recreate the PR but the fork is no longer available. :(

**Comment by SaltSouls** [comment]
> Oh no-- did you already get rid of your fork? I need to reset the branch and was going to ask you to recreate the PR but the fork is no longer available. :(

Oh boy. Gimme a bit and I will re-upload a forked version. Thought you had already merged everything into the main branch. Sorry about that.

**Pull request merged**
